### ISSUE TITLE
Missing kerbalEVAVintage and kerbalEVAfemaleVintage

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-RO/TacLifeSupport#117]
The expansion added these two new kerbal parts, you don't have them in the code as of now, at this location:

https://github.com/KSP-RO/TacLifeSupport/blob/49eba6ba1e7d4498a7ff0550d28b8014b1a4fdd9/Source/AddLifeSupport.cs#L57

I also didn't see the kerbalEVAfemale there

**Comment by JPLRepo** [comment]
because that's not how it works.
There was an issue regarding MH kerbals if you didn't have MH installed which has already been fixed.

**Comment by 7ranceaddic7** [comment]
how does it work?  Maybe you could provide some insight into [this](https://forum.kerbalspaceprogram.com/index.php?/topic/179030-141151-tweakscale-under-new-management-2018-1127/&do=findComment&comment=3479630) problem.

**Comment by JPLRepo** [comment]
Yeah they should try using null checks.

**Comment by linuxgurugamer** [comment]
What was the issue about missing MH kerbals, apparently one of my mods is running up against that as well.
Thanks

**Comment by linuxgurugamer** [comment]
And I see that I misread the line, sorry for the false alarm

**Comment by JPLRepo** [comment]
PartLoader.LoadedPartsList contains a reference to the Kerbal prefabs for Making History even if they are not installed.
So you have to null check them.
OR... you can just use MM to amend the Prebuilt parts in stock and MH and not have to do it in code.
TAC LS doesn't do that because it adds different resource amounts to the Kerbal parts depending on user settings.

**Comment by linuxgurugamer** [comment]
Thanks.
