### ISSUE TITLE
Generators not producing EC during background processing

### ISSUE THREAD

**Issue by Gilph** [KSP-RO/TacLifeSupport#118]
I have three space stations that use stock solar panels and a lander on the surface of Minmus that uses two Near Future MX-0 generators. During warp (never higher than 7), the stations update their EC usage nicely, but the lander ﻿never updates. I read that generators should also work in background.

If I turn off the background processing, both the solar panels and the generators work the same way, using estimation and catch-up. If I enable it, only the solar panels generate EC. The only workaround is to put a lot of battery on a ship and make it active before lack of EC harms Kerbals.

**Comment by JPLRepo** [comment]
Sorry I'm not familiar with this mod. Out of the box. TAC LS works with any part/part mod using the stock generator module. My guess is this mod does not.
I looked at Near Future mods but I couldn't find the MX-0 generator. Can you please supply a link to the mod you are using thanks.

**Comment by MBradbury** [comment]
I'm also having this issue. It looks like it is because [NFE](https://github.com/ChrisAdderley/NearFutureElectrical/blob/master/GameData/NearFutureElectrical/Parts/FissionReactors/reactor-0625/reactor-0625.cfg) uses [FissionGenerator](https://github.com/ChrisAdderley/NearFutureElectrical/blob/665375f7b4b91c3ecbe596d6b56fa5a72993373d/Source/NearFutureElectrical/FissionGenerator.cs) for its nuclear reactors.

**Comment by JPLRepo** [comment]
This has now been added.
