### ISSUE TITLE
1.1.3 Support

### ISSUE THREAD

**Issue by tophyr** [KSP-RO/TacLifeSupport#26]

**Comment by james3838** [comment]
Is there specific you are having with 1.1.3?  I haven't tried it out yet.  Make sure you post any exceptions from KSP.log found in directory where ksp.exe is.  Logs from this mod start with "[TLS-"

**Comment by ardaric** [comment]
I encountered a problem concerning the the remaining time until the life support ressources are gone in the overview window. Since the update, they show negative numbers which are decreasing with time (showing even bigger negative values).

Without further reasearch, it seems the absolute values represents the correct number, but is handled as a negative number an further decreased when time goes by. 
Resources from the containers are still consumed though.

The logfile is showing tons of exceptions with the exact same text:

`[EXC 00:42:28.437] MissingMethodException: Method not found: 'TimeWarp.SetRate'.
    Tac.LifeSupportController.FixedUpdate ()`

Playing on Linux via Steam:

`Kerbal Space Program - 1.1.3.1289 (LinuxPlayer)
OS: Linux 3.13 Ubuntu 14.04 64bit
CPU: Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz (4)
RAM: 7950
GPU: GeForce GTX 960/PCIe/SSE2 (2048MB)
SM: 30 (OpenGL 4.5 [4.5.0 NVIDIA 349.16])
RT Formats: ARGB32, Depth, ARGBHalf, Shadowmap, RGB565, ARGB4444, ARGB1555, Default, ARGB2101010, DefaultHDR, ARGBFloat, RGFloat, RGHalf, RFloat, RHalf, R8`

For any further information, just ask, I'm unsure what info might be helpful and I don't want to spam the entire log in here.

**Comment by james3838** [comment]
I recompiled locally and resolved those issues.  Need Dan to build and release linking to new 1.1.3 dlls.

**Comment by danfarnsy** [comment]
Oh, look! Time for an update! I'll get on it.

**Comment by keyspace** [comment]
EDIT: Strike this, my first manual deployment failed. A proper rebuild works fine.

---

@james3838 I recompiled locally and it didn't. However, I'm on Linux, with `xbuild` instead of `MSBuild`, so had to fiddle with `CommonProperties.proj` and deploy manually, which is error-prone.

(EDIT: also, I'm using a save file that's had at least one run with non-updated mod.)

Anyway, I'll try and see what's causing this. A straightforward entry point is `LifeSupportMonitoringWindow.cs:170`.

**Comment by NathanKell** [comment]
Since this is out for 1.1.3 I'm closing this. :) Cheers to @danfarnsy 

Also, I took the liberty of removing the extra source zip from the release--Github automatically links the source from when the release is tagged, so no need to do that (and it confuses CKAN). Closes https://github.com/KSP-CKAN/NetKAN/issues/4340

**Comment by danfarnsy** [comment]
I noticed the extra links, but I didn't realize they were problematic for CKAN, as I haven't updated my RO install. Thanks, @NathanKell for fixing it.
