### ISSUE TITLE
Incompatibility with RO

### ISSUE THREAD

**Issue by danielguo** [KSP-RO/TacLifeSupport#39]
Realism Overhaul overrides the resource definition in PluginData. In 0.12.3 and also 0.12.4, even with the file provided by RO in PluginData, TAC-LS is still using the default resource consumption rate.

**Comment by JPLRepo** [comment]
The file should be in \GameData\ThunderAeroSpace\TacLifeSupport.
NOT the PluginData folder.
If you move the RO provided cfg file and overwrite the TAC one in the folder above shoul be fixed with 0.12.4.
0.12.3 had a problem where it wasn't reading the cfg file at all (my typo).
Can you overwrite the cfg file from RO over the TAC one in the folder above and confirm it appears fixed for now?
I have submitted a request to have RO change to put the cfg in the right folder.

**Comment by JPLRepo** [comment]
Am going to make additional changes to support RO a bit better and also improve chance of Module Manager doing a cache re-build.
a) LifeSupport.Cfg will be static file. (currently user can udpate the values in this file)
b) RO can create a Module Manager file to update LifeSupport.Cfg base settings.
c) User changes to these settings will be stored in save game persistent.sfs file. TAC LS will apply these user changes OVER the base changes on startup.
These changes resolve a few problems. Like;
MM rebuilding it's cache. 
Using an MM file for RO means it doesn't matter what order the user installs the mods in.
Settings for consumption rates etc can be set per save game instead of per install.

@NathanKell  - Will track these changes via here. Will create PR for RO when done as well (for MM file and remove existing overwrite cfg file).

**Comment by danielguo** [comment]
> If you move the RO provided cfg file and overwrite the TAC one in the folder above shoul be fixed with 0.12.4.

Yeah, I did that and worked correctly.

**Comment by JPLRepo** [comment]
V0.12.5 Supports everything required. I have tested and it works.
I have an MM file for RO that I will put into a PR to RO once I have also made the changes for RO for TACLS converters as they have changed in V0.12.5, and this MM file also needs updating.
Leaving open until PR is made on RO.
