### ISSUE TITLE
Cherrydev's changes

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/TacLifeSupport#4]
@cherrydev AFAIK we still haven't gotten your changes yet. Can you please upload them _somewhere_ ASAP? We're having to duplicate the work.

Failing that @taraniselsu if you do have the stuff @cherrydev sent you, could you upload that?

**Comment by taraniselsu** [comment]
The link they gave me is:
https://drive.google.com/open?id=0B5xHcWOVyLd9Nkl2ZnVaMVdHNXc

**Comment by NathanKell** [comment]
thanks so much! :)
@danfarnsy ^^^^

**Comment by taraniselsu** [comment]
Also, did you see @james3838's changes?
https://github.com/taraniselsu/TacLib/pull/6 and https://github.com/taraniselsu/TacLifeSupport/pull/92

**Comment by NathanKell** [comment]
I believe @danfarnsy has already merged them in, yep!

**Comment by james3838** [comment]
Just wanted to note that @cherrydev paths are relative instead of using Environment variable KSP.  I think that should be fixed to stay consistent with original.  

Also I noticed that the submodule was flattened.  Was that intentional?  Is the other project that was using no longer in existence? 

One other note, is this the future repo?  I'd love to contribute.  I'm new to KSP modding, but an experienced c# dev.  Would be interested in helping contribute.  You communicate on Slack or IRC?

**Comment by NathanKell** [comment]
That branch is merely to have a working, forum-legal TACLS out while the main ksp11update branch trundles forward.

**Comment by cherrydev** [comment]
@james3838 No, the flattening of the submodule wasn't intentional on my end, and in fact I hadn't even noticed that it was a submodule at first.  Perhaps it's being used by TAC Fuel Balancer?  I'm not sure.

**Comment by james3838** [comment]
@cherrydev yah - I think that was what it was for.  I don't use that mod, so I don't mind, but @taraniselsu might.  :)

**Comment by danfarnsy** [comment]
The flattening was on my end, and yes it was intentional. @taraniselsu 's original fork for TacLib is still intact. I'm sure I was making mistakes along the way in trying to get things to point to an updated fork instead of Taranis's original master branch, but I simply decided it was faster and easier for our fork to flatten it since we don't intend to use TacLib for other mods. It doesn't keep with the spirit of sharing, I know, but there are costs to my present learning curve.
