### ISSUE TITLE
Life Support Module not giving resources

### ISSUE THREAD

**Issue by demib72** [KSP-RO/TacLifeSupport#54]
[output_log2.txt](https://github.com/KSP-RO/TacLifeSupport/files/547129/output_log2.txt)

As the title states, I am not getting TACLS resources added to parts with crews despite it saying it has a life support module. I am assuming it is this that I am having issues with. I tried removing all mods I have to see if there was a conflict, but only capsules are getting updated. The stock lab and hitchhiker parts received nothing.

**Comment by JPLRepo** [comment]
That's because they aren't meant to.
Having the Life Support module means the crew inside get oxygen, and supplies supplied to them.
It does not mean that part gets supplies added to it.
The only parts that do have supplies added to them are ones with ModuleCommand that can hold crew.
Or of course the TAC LS resource containers.

**Comment by demib72** [comment]
Ahhhh, I remember before that parts with crew would get it. Perhaps it was a MM config or something. Thanks for the explanation.

**Comment by JPLRepo** [comment]
No Problems.
